### ISSUE TITLE
'make all' missed in the Section Install & Trick Movidius SDK

### ISSUE THREAD

**Issue by octavianx** [acharroux/Movidius-On-MacOS#2]
During  the steps of  'Trick the Makefile & generate the only mandatory component on Mac OS: libmvnc.so':

there should be a 'make all'  before 'sudo make basicinstall pythoninstall'
or you'll get an Error of 

```bash
mkdir -p /usr/local/include/
mkdir -p /usr/local/lib/
cp obj-x86_64/libmvnc.so.0 /usr/local/lib/
ln -fs libmvnc.so.0 /usr/local/lib/libmvnc.so
cp ../include/*.h /usr/local/include/
mkdir -p /usr/local/lib/mvnc
cp mvnc/MvNCAPI.mvcmd /usr/local/lib/mvnc/
cp: mvnc/MvNCAPI.mvcmd: No such file or directory
make: *** [basicinstall] Error 1
```

**Comment by hequn** [comment]
@octavianx Thanks!

**Comment by Telectroboy** [comment]
Thanks!!!

**Comment by duocang** [comment]
@octavianx @hequn @Telectroboy 
Hi! Thank you for your help.

The help is great. But it would be nice you guys can send a pull request in the future when error fixed.

I did already.
