### ISSUE TITLE
mvNCCompile command not found

### ISSUE THREAD

**Issue by piaodangdang** [acharroux/Movidius-On-MacOS#4]
when I run make compile in the dir example/tensorflow  bash prompt  mvNCCompile command not found , How can I fix it

**Comment by duocang** [comment]
@piaodangdang how is now?

**Comment by acharroux** [comment]
As said in readme:
The NCSDK tools: these tools allows to translate (and validate the translation) machine learning models to Movidius format so they can be run by the Movidius key. This part is the most complex and not (not yet) supported on Mac OS. Note this part does not need a Movidius key to be actually present.

mvnCCCompile is part of these tools and therefore, cannot be run on MacOS at least with this version of SDK.  You have to use a supported platform to compile the model for Movidius key. Then you can use this git to deploy the result of compilation and hosting its execution on Mac.

Note also that with new Movidius hardware key, Intel has totally changed its mind:
* Movidius SDK (both version 1 & 2) has been replaced by their global OpenVINO sdk. 
* OpenVino can drive both versions of Movidius hardware key. 
* Last but not least, there is a version of OpenVINO sdk for MacOS (I have not tested it)

So as a conclusion this git repo fix an issue that is no more existing :)
